# Generated by Django 5.2.3 on 2025-06-23 16:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('niveau', models.CharField(max_length=20)),
                ('annee_scolaire', models.CharField(default='2024-2025', max_length=10)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('coefficient', models.FloatField(default=1.0)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('annee_scolaire', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='TypeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('coefficient', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('numero_etudiant', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=15)),
                ('adresse', models.TextField(blank=True)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='APP.classe')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_generale', models.FloatField(blank=True, null=True)),
                ('rang', models.IntegerField(blank=True, null=True)),
                ('appreciation_generale', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='APP.etudiant')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.trimestre')),
            ],
            options={
                'ordering': ['-trimestre__date_debut'],
                'unique_together': {('etudiant', 'trimestre')},
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=15)),
                ('classes', models.ManyToManyField(related_name='professeurs', to='APP.classe')),
                ('matieres', models.ManyToManyField(related_name='professeurs', to='APP.matiere')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoteTrimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne', models.FloatField(blank=True, null=True)),
                ('appreciation', models.TextField(blank=True)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_trimestre', to='APP.bulletin')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.matiere')),
            ],
            options={
                'unique_together': {('bulletin', 'matiere')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField(help_text='Note sur 20', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('date_evaluation', models.DateField()),
                ('commentaire', models.TextField(blank=True)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='APP.etudiant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.matiere')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.professeur')),
                ('type_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.typeevaluation')),
            ],
            options={
                'ordering': ['-date_evaluation'],
                'unique_together': {('etudiant', 'matiere', 'type_evaluation', 'date_evaluation')},
            },
        ),
    ]
