# Generated by Django 5.2.3 on 2025-06-23 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeevaluation',
            name='coefficient',
        ),
    ]
